const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// Build a unique, SEO-friendly FAQ set per product from its data.
function buildFaq(p) {
  const faq = [
    {
      q: `What is ${p.name} used for?`,
      a: `${p.name} is used for ${p.applications.toLowerCase()}. ${p.short_desc}`
    },
    {
      q: `What sizes and grades of ${p.name} are available in Noida?`,
      a: `We supply ${p.name} in ${p.sizes.toLowerCase()}. ${p.grades ? ('Available grades/variants: ' + p.grades + '.') : ''} Custom cutting to your project size is available.`
    },
    {
      q: `What is the price of ${p.name} in Noida?`,
      a: `${p.name} starts from ${p.price_from}. Final pricing depends on grade, size and quantity. Call 9910238277 or WhatsApp us for an exact quote with same-day response.`
    },
    {
      q: `Do you deliver ${p.name} to Greater Noida, Delhi, Ghaziabad, Faridabad and Gurugram?`,
      a: `Yes. Garg Industrial Mesh delivers ${p.name} across Noida, Greater Noida, Delhi, Ghaziabad, Faridabad and Gurugram with same-day dispatch for in-stock items.`
    },
    {
      q: `Is ${p.name} available in bulk for project orders?`,
      a: `Yes. We supply ${p.name} in bulk for construction, industrial and architectural projects at direct manufacturer wholesale rates. Contact us for a project quote.`
    }
  ];
  return JSON.stringify(faq);
}

const products = [
  {
    name: 'SS Welded Mesh',
    category: 'Welded Mesh',
    short_desc: 'Stainless steel welded wire mesh in grade 201 and 304 for industrial, filtration and security use.',
    description: 'SS Welded Mesh is manufactured from stainless steel wire resistance-welded at every intersection to form a rigid, corrosion-resistant grid. Available in grades 201 and 304, it offers excellent strength, weld integrity and surface finish. Ideal for filtration, security screens, machine guards, food processing, architectural panels and agricultural use in Noida, Greater Noida and Delhi NCR.',
    materials: 'Stainless Steel 201, Stainless Steel 304',
    sizes: '12mm to 150mm opening, 0.5mm to 5mm wire thickness, 3ft x 8ft / 4ft x 8ft sheets, rolls available',
    grades: 'SS 201, SS 304',
    applications: 'Filtration, Security Screens, Machine Guards, Food Processing, Architectural Panels, Agriculture',
    price_from: '₹85/sqft',
    meta_title: 'SS Welded Mesh Supplier in Noida | SS 201 & 304 Welded Wire Mesh',
    meta_description: 'Buy SS welded mesh (grade 201 & 304) in Noida from Garg Industrial Mesh. Corrosion-resistant stainless steel welded wire mesh sheets & rolls. Get a free quote today.',
    meta_keywords: 'ss welded mesh, stainless steel welded mesh, ss 304 welded mesh, ss 201 welded mesh, welded wire mesh noida, ss welded mesh supplier',
    featured: 1
  },
  {
    name: 'GI Welded Mesh',
    category: 'Welded Mesh',
    short_desc: 'Galvanised iron welded mesh for fencing, poultry and construction — rust-resistant and economical.',
    description: 'GI Welded Mesh is made from hot-dip galvanised iron wire welded at each intersection, providing a strong, rust-resistant and economical mesh. Widely used for boundary fencing, poultry farms, construction reinforcement, gabions and safety partitions across Noida, Ghaziabad and Delhi NCR.',
    materials: 'Galvanised Iron (GI) Wire',
    sizes: '25mm to 100mm opening, 1.6mm to 4mm wire, 3ft/4ft/6ft width, 18m rolls',
    grades: 'Standard GI',
    applications: 'Boundary Fencing, Poultry Farms, Construction Reinforcement, Gabions, Safety Partitions',
    price_from: '₹45/sqft',
    meta_title: 'GI Welded Mesh Supplier in Noida | Galvanised Welded Wire Mesh',
    meta_description: 'GI welded mesh in Noida from Garg Industrial Mesh. Rust-resistant galvanised iron welded wire mesh for fencing, poultry & construction. Best wholesale prices.',
    meta_keywords: 'gi welded mesh, galvanised welded mesh, gi welded wire mesh, gi mesh noida, gi welded mesh supplier, poultry mesh',
    featured: 1
  },
  {
    name: 'MS Welded Mesh',
    category: 'Welded Mesh',
    short_desc: 'Mild steel welded mesh for heavy-duty construction, slabs and precast applications.',
    description: 'MS Welded Mesh is manufactured from mild steel wire welded into a precise grid, offering high tensile strength for structural use. Commonly used in RCC slabs, precast elements, road reinforcement, retaining walls and heavy industrial screening in Greater Noida and Delhi NCR.',
    materials: 'Mild Steel (MS) Wire',
    sizes: '50mm to 200mm opening, 2mm to 8mm wire, 4ft/6ft/8ft width',
    grades: 'MS Standard',
    applications: 'RCC Slabs, Precast Elements, Road Reinforcement, Retaining Walls, Industrial Screening',
    price_from: '₹40/sqft',
    meta_title: 'MS Welded Mesh Supplier in Noida | Mild Steel Welded Wire Mesh',
    meta_description: 'MS welded mesh in Noida from Garg Industrial Mesh. High-strength mild steel welded wire mesh for construction, slabs & precast. Wholesale rates, fast delivery.',
    meta_keywords: 'ms welded mesh, mild steel welded mesh, ms welded wire mesh, construction mesh noida, ms mesh supplier',
    featured: 0
  },
  {
    name: 'MS Perforated Sheet',
    category: 'Perforated Sheet',
    short_desc: 'Mild steel perforated sheets in 3x8 and 4x8 ft sizes — for sieves, guards and acoustic panels.',
    description: 'MS Perforated Sheet is a mild steel panel punched with precise round, square or slot holes. Supplied in 3x8 ft and 4x8 ft standard sizes, it is used for sieves, vibrating screens, machine guards, acoustic panels, ventilation and decorative facades. Strong, weldable and paintable for industrial and architectural use in Noida and Delhi NCR.',
    materials: 'Mild Steel (MS) Sheet',
    sizes: '3ft x 8ft, 4ft x 8ft; thickness 1mm to 6mm; round/square/slot holes',
    grades: 'MS Standard',
    applications: 'Sieves, Vibrating Screens, Machine Guards, Acoustic Panels, Ventilation, Decorative Facades',
    price_from: '₹120/sqft',
    meta_title: 'MS Perforated Sheet Supplier in Noida | 3x8 & 4x8 MS Perforated Sheets',
    meta_description: 'MS perforated sheet in Noida from Garg Industrial Mesh. Mild steel perforated panels in 3x8 & 4x8 ft for sieves, guards & acoustic use. Custom hole patterns. Get quote.',
    meta_keywords: 'ms perforated sheet, mild steel perforated sheet, perforated sheet noida, 4x8 perforated sheet, 3x8 perforated sheet, ms perforated sheet supplier, copper brass aluminium perforated sheet',
    featured: 1
  },
  {
    name: 'SS Perforated Sheet',
    category: 'Perforated Sheet',
    short_desc: 'Stainless steel perforated sheets in grade 202 and 304 — corrosion-resistant and decorative.',
    description: 'SS Perforated Sheet is punched from stainless steel in grades 202 and 304, combining corrosion resistance with a clean architectural finish. Used for filtration, food-grade screens, facades, sun louvres, balustrade infill and acoustic panels in Noida, Greater Noida and Delhi NCR.',
    materials: 'Stainless Steel 202, Stainless Steel 304',
    sizes: '4ft x 8ft standard; thickness 0.5mm to 5mm; round/square/slot/decorative holes',
    grades: 'SS 202, SS 304',
    applications: 'Filtration, Food-Grade Screens, Facades, Sun Louvres, Balustrade Infill, Acoustic Panels',
    price_from: '₹220/sqft',
    meta_title: 'SS Perforated Sheet Supplier in Noida | SS 202 & 304 Perforated Sheets',
    meta_description: 'SS perforated sheet (grade 202 & 304) in Noida from Garg Industrial Mesh. Corrosion-resistant stainless steel perforated panels for filtration & facades. Request a quote.',
    meta_keywords: 'ss perforated sheet, stainless steel perforated sheet, ss 304 perforated sheet, ss 202 perforated sheet, perforated sheet noida, ss perforated sheet supplier',
    featured: 1
  },
  {
    name: 'GI Perforated Sheet',
    category: 'Perforated Sheet',
    short_desc: 'Galvanised perforated sheets — rust-resistant and economical for outdoor and industrial use.',
    description: 'GI Perforated Sheet is a hot-dip galvanised mild steel panel punched with round or square holes, offering rust resistance at an economical price. Ideal for outdoor sieves, ventilation grilles, walkway gratings, agricultural screens and noise barriers across Noida, Ghaziabad and Delhi NCR.',
    materials: 'Galvanised Iron (GI) Sheet',
    sizes: '4ft x 8ft; thickness 1mm to 4mm; round/square holes',
    grades: 'Standard GI',
    applications: 'Outdoor Sieves, Ventilation Grilles, Walkway Gratings, Agricultural Screens, Noise Barriers',
    price_from: '₹160/sqft',
    meta_title: 'GI Perforated Sheet Supplier in Noida | Galvanised Perforated Sheet',
    meta_description: 'GI perforated sheet in Noida from Garg Industrial Mesh. Rust-resistant galvanised perforated panels for outdoor & industrial use. Best wholesale prices. Get quote.',
    meta_keywords: 'gi perforated sheet, galvanised perforated sheet, gi perforated panel, perforated sheet noida, gi perforated sheet supplier',
    featured: 0
  },
  {
    name: 'Copper Perforated Sheet',
    category: 'Perforated Sheet',
    short_desc: 'Copper perforated sheets with round or hexagonal holes — facades, EMI shielding and heritage work.',
    description: 'Copper Perforated Sheet is punched from pure copper plate with precise round, hexagonal or decorative holes. It develops a natural patina over time and is valued for architectural cladding, temple and heritage work, EMI/RFI shielding, decorative screens, ventilation panels and premium interiors. Supplied cut-to-size across Noida, Greater Noida and Delhi NCR by Garg Industrial Mesh.',
    materials: 'Copper Sheet',
    sizes: 'Cut to size; thickness 0.5mm to 3mm; round/hexagonal/square/decorative holes',
    grades: 'Electrolytic Tough Pitch (ETP) Copper, Commercial Copper',
    applications: 'Architectural Facades, Heritage & Temple Work, EMI Shielding, Decorative Screens, Ventilation Panels, Premium Interiors',
    price_from: '₹450/sqft',
    meta_title: 'Copper Perforated Sheet Supplier in Noida | Hexagonal & Round Copper Perforated Metal',
    meta_description: 'Copper perforated sheet in Noida — round & hexagonal holes for facades, heritage work, EMI shielding & ventilation. Cut to size. Garg Industrial Mesh. Call 9910238277.',
    meta_keywords: 'copper perforated sheet, hexagonal copper perforated sheet, copper perforated sheet noida, copper perforated metal, decorative copper sheet delhi ncr',
    featured: 1
  },
  {
    name: 'Brass Perforated Sheet',
    category: 'Perforated Sheet',
    short_desc: 'Brass perforated sheets for ornamental screens, nameplates and decorative architectural work.',
    description: 'Brass Perforated Sheet is punched from brass alloy with round, square or ornamental hole patterns. It offers a warm golden finish for decorative screens, nameplates, furniture inlays, acoustic panels and architectural detailing. Corrosion-resistant for indoor and semi-outdoor use. Cut to size and supplied across Noida and Delhi NCR by Garg Industrial Mesh.',
    materials: 'Brass Sheet',
    sizes: 'Cut to size; thickness 0.5mm to 3mm; round/square/ornamental holes',
    grades: 'Cartridge Brass, Yellow Brass, Commercial Brass',
    applications: 'Ornamental Screens, Nameplates, Furniture Inlays, Acoustic Panels, Architectural Detailing',
    price_from: '₹400/sqft',
    meta_title: 'Brass Perforated Sheet Supplier in Noida | Decorative Brass Perforated Metal',
    meta_description: 'Brass perforated sheet in Noida from Garg Industrial Mesh. Decorative brass perforated metal for screens, nameplates & architecture. Cut to size. Call 9910238277.',
    meta_keywords: 'brass perforated sheet, brass perforated sheet noida, brass perforated metal, decorative brass sheet, brass perforated panel supplier delhi ncr',
    featured: 1
  },
  {
    name: 'Aluminium Perforated Sheet',
    category: 'Perforated Sheet',
    short_desc: 'Lightweight aluminium perforated sheets for facades, ceilings, HVAC and acoustic panels.',
    description: 'Aluminium Perforated Sheet is a lightweight, corrosion-resistant panel punched with round, square or slot holes. Ideal for building facades, false ceilings, HVAC grilles, acoustic panels, sunscreens and machine guards where weight savings matter. Easy to cut, powder-coat and install. Supplied in standard and cut-to-size sheets across Noida, Greater Noida and Delhi NCR by Garg Industrial Mesh.',
    materials: 'Aluminium Sheet',
    sizes: '4ft x 8ft standard; cut to size; thickness 0.5mm to 3mm; round/square/slot holes',
    grades: 'AA 1100, AA 3003, AA 5052',
    applications: 'Facades, False Ceilings, HVAC Grilles, Acoustic Panels, Sunscreens, Lightweight Guards',
    price_from: '₹180/sqft',
    meta_title: 'Aluminium Perforated Sheet Supplier in Noida | Aluminum Perforated Metal',
    meta_description: 'Aluminium perforated sheet in Noida from Garg Industrial Mesh. Lightweight aluminum perforated metal for facades, ceilings & HVAC. Cut to size. Call 9910238277.',
    meta_keywords: 'aluminium perforated sheet, aluminum perforated sheet, aluminium perforated sheet noida, aluminium perforated metal, aluminum perforated panel supplier delhi ncr',
    featured: 1
  },
  {
    name: 'MS Expanded Mesh',
    category: 'Expanded Mesh',
    short_desc: 'Mild steel expanded mesh (diamond / barfi jali) for walkways, fencing, guards and plastering.',
    description: 'MS Expanded Mesh is made by slitting and stretching mild steel sheet into a diamond (barfi jali) pattern — no welds, high strength-to-weight. Used for walkway gratings, machine guards, fencing infill, plastering lath, catwalks, filters and security screens. Strong, weldable and economical for construction and industrial projects across Noida and Delhi NCR. Also called expanded metal sheet or MS jali.',
    materials: 'Mild Steel (MS) Sheet',
    sizes: 'Standard sheets & cut to size; fine to heavy SWD/LWD openings; raised or flattened',
    grades: 'MS Standard, Flattened / Raised',
    applications: 'Walkway Gratings, Machine Guards, Fencing Infill, Plastering Lath, Catwalks, Security Screens, Industrial Filters',
    price_from: '₹95/sqft',
    meta_title: 'MS Expanded Mesh Supplier in Noida | Mild Steel Expanded Metal / Barfi Jali',
    meta_description: 'MS expanded mesh (barfi jali) in Noida for walkways, guards, fencing & plastering. Diamond expanded metal sheet cut to size. Garg Industrial Mesh. Call 9910238277.',
    meta_keywords: 'ms expanded mesh, mild steel expanded mesh, expanded metal sheet noida, barfi jali, ms expanded metal, expanded mesh supplier delhi ncr',
    featured: 1
  },
  {
    name: 'GI Expanded Mesh',
    category: 'Expanded Mesh',
    short_desc: 'Galvanised expanded mesh for outdoor walkways, fencing, ventilation and anti-slip platforms.',
    description: 'GI Expanded Mesh is galvanised expanded metal with a zinc coating for rust resistance outdoors. Diamond openings give grip and airflow for walkways, stair treads, fencing, ventilation panels, compound walls and agricultural screens. Economical outdoor alternative to stainless expanded mesh across Noida, Ghaziabad and Delhi NCR.',
    materials: 'Galvanised Iron (GI) Sheet',
    sizes: 'Sheets & cut to size; raised or flattened diamond openings',
    grades: 'Standard GI Expanded / Flattened',
    applications: 'Outdoor Walkways, Stair Treads, Boundary Fencing, Ventilation Panels, Compound Walls, Agricultural Screens',
    price_from: '₹120/sqft',
    meta_title: 'GI Expanded Mesh Supplier in Noida | Galvanised Expanded Metal Sheet',
    meta_description: 'GI expanded mesh in Noida — rust-resistant galvanised expanded metal for outdoor walkways, fencing & ventilation. Cut to size. Call 9910238277.',
    meta_keywords: 'gi expanded mesh, galvanised expanded mesh, gi expanded metal sheet, expanded mesh noida, gi barfi jali',
    featured: 0
  },
  {
    name: 'SS Expanded Mesh',
    category: 'Expanded Mesh',
    short_desc: 'Stainless steel expanded mesh for facades, food plants, filters and premium architectural screens.',
    description: 'SS Expanded Mesh is slit-and-stretched stainless steel (typically SS 304/202) forming a durable diamond pattern. Used for building facades, balustrade infill, food-grade platforms, chemical plant flooring, machine guards, filters and decorative screens where corrosion resistance and a clean finish matter. Supplied across Noida and Delhi NCR by Garg Industrial Mesh.',
    materials: 'Stainless Steel 202, Stainless Steel 304',
    sizes: 'Sheets & cut to size; fine to heavy diamond openings; raised or flattened',
    grades: 'SS 202, SS 304',
    applications: 'Facades, Balustrade Infill, Food-Grade Platforms, Chemical Plant Flooring, Machine Guards, Filters, Decorative Screens',
    price_from: '₹280/sqft',
    meta_title: 'SS Expanded Mesh Supplier in Noida | SS 304 Expanded Metal Sheet',
    meta_description: 'SS expanded mesh (SS 304/202) in Noida for facades, food plants, filters & architectural screens. Corrosion-resistant expanded metal. Call 9910238277.',
    meta_keywords: 'ss expanded mesh, stainless steel expanded mesh, ss 304 expanded metal, expanded mesh noida, ss expanded metal sheet',
    featured: 1
  },
  {
    name: 'Aluminium Expanded Mesh',
    category: 'Expanded Mesh',
    short_desc: 'Lightweight aluminium expanded mesh for ceilings, facades, sunscreens and HVAC grilles.',
    description: 'Aluminium Expanded Mesh is a light, corrosion-resistant diamond mesh used where weight savings matter — false ceilings, facade cladding, sunscreens, HVAC return grilles, speaker grilles and decorative partitions. Easy to cut, powder-coat and install. Ideal for architects and fit-outs across Noida, Greater Noida and Delhi NCR.',
    materials: 'Aluminium Sheet',
    sizes: 'Sheets & cut to size; fine to medium diamond openings',
    grades: 'AA 1100, AA 3003, AA 5052',
    applications: 'False Ceilings, Facade Cladding, Sunscreens, HVAC Grilles, Speaker Grilles, Decorative Partitions',
    price_from: '₹160/sqft',
    meta_title: 'Aluminium Expanded Mesh Supplier in Noida | Aluminum Expanded Metal',
    meta_description: 'Aluminium expanded mesh in Noida for ceilings, facades, sunscreens & HVAC grilles. Lightweight expanded metal cut to size. Call 9910238277.',
    meta_keywords: 'aluminium expanded mesh, aluminum expanded mesh, aluminium expanded metal noida, aluminium barfi jali, expanded aluminium sheet',
    featured: 1
  },
  {
    name: 'Copper Expanded Mesh',
    category: 'Expanded Mesh',
    short_desc: 'Copper expanded mesh for decorative facades, heritage screens, EMI shielding and premium interiors.',
    description: 'Copper Expanded Mesh is slit-and-stretched copper sheet forming a continuous diamond pattern (no welds). Used for decorative architectural facades, heritage and temple screens, EMI/RFI shielding cages, luxury interior partitions, radiator grilles and artistic cladding. Develops a natural patina outdoors. Cut-to-size and roll supply available from Garg Industrial Mesh, Sector 9 Noida.',
    materials: 'Copper Sheet',
    sizes: 'Sheets, rolls & cut to size; fine to medium diamond openings',
    grades: 'ETP Copper, Commercial Copper',
    applications: 'Decorative Facades, Heritage Screens, EMI/RFI Shielding, Luxury Interiors, Radiator Grilles, Artistic Cladding',
    price_from: '₹480/sqft',
    meta_title: 'Copper Expanded Mesh Supplier in Noida | Decorative Copper Expanded Metal',
    meta_description: 'Copper expanded mesh in Noida for decorative facades, heritage screens & EMI shielding. Diamond copper expanded metal cut to size. Call 9910238277.',
    meta_keywords: 'copper expanded mesh, copper expanded metal, copper expanded mesh noida, decorative copper mesh, copper diamond mesh delhi ncr',
    featured: 1
  },
  {
    name: 'Brass Expanded Mesh',
    category: 'Expanded Mesh',
    short_desc: 'Brass expanded mesh for ornamental screens, nameplates, furniture and architectural detailing.',
    description: 'Brass Expanded Mesh is expanded brass sheet with a warm golden diamond pattern. Used for ornamental screens, furniture inlays, nameplate backing, acoustic/decorative panels, boutique storefronts and premium architectural detailing. Corrosion-resistant for indoor and semi-outdoor use. Supplied cut-to-size across Noida and Delhi NCR by Garg Industrial Mesh.',
    materials: 'Brass Sheet',
    sizes: 'Sheets & cut to size; fine to medium diamond openings',
    grades: 'Cartridge Brass, Yellow Brass, Commercial Brass',
    applications: 'Ornamental Screens, Furniture Inlays, Nameplate Backing, Decorative Panels, Boutique Storefronts, Architectural Detailing',
    price_from: '₹420/sqft',
    meta_title: 'Brass Expanded Mesh Supplier in Noida | Decorative Brass Expanded Metal',
    meta_description: 'Brass expanded mesh in Noida for ornamental screens, furniture & architectural detailing. Golden diamond brass expanded metal. Call 9910238277.',
    meta_keywords: 'brass expanded mesh, brass expanded metal, brass expanded mesh noida, decorative brass mesh, brass diamond mesh delhi ncr',
    featured: 1
  },
  {
    name: 'SS Wire Mesh',
    category: 'Wire Mesh',
    short_desc: 'Woven stainless steel wire mesh in grade 202 and 304 — fine filtration and screening.',
    description: 'SS Wire Mesh is woven from stainless steel wire in grades 202 and 304, available in fine to coarse meshes. Used for liquid and gas filtration, sieving, test sieves, security screens, insect screening and architectural mesh in Noida, Greater Noida and Delhi NCR. High tensile strength and excellent corrosion resistance.',
    materials: 'Stainless Steel 202, Stainless Steel 304',
    sizes: '10 mesh to 500 mesh; wire 0.025mm to 3mm; rolls and cut pieces',
    grades: 'SS 202, SS 304',
    applications: 'Liquid & Gas Filtration, Sieving, Test Sieves, Security Screens, Insect Screening, Architectural Mesh',
    price_from: '₹95/sqft',
    meta_title: 'SS Wire Mesh Supplier in Noida | SS 202 & 304 Woven Wire Mesh',
    meta_description: 'SS wire mesh (grade 202 & 304) in Noida from Garg Industrial Mesh. Woven stainless steel wire mesh for filtration, sieving & screening. Fine to coarse meshes. Get quote.',
    meta_keywords: 'ss wire mesh, stainless steel wire mesh, ss 304 wire mesh, ss 202 wire mesh, wire mesh noida, ss wire mesh supplier, woven wire mesh',
    featured: 1
  },
  {
    name: 'PVC Mesh',
    category: 'Fencing Mesh',
    short_desc: 'PVC coated welded mesh in 4ft, 4.5ft, 5ft and 6.5ft heights — durable and weatherproof.',
    description: 'PVC Mesh is a welded wire mesh coated with a UV-stabilised PVC layer, offering excellent weather resistance and a clean look. Available in 4ft, 4.5ft, 5ft and 6.5ft heights, it is widely used for boundary fencing, garden fencing, pet enclosures, sports courts and farm partitions in Noida and Delhi NCR.',
    materials: 'GI Wire with PVC Coating',
    sizes: '4ft, 4.5ft, 5ft, 6.5ft heights; opening 25mm to 75mm; 18m rolls',
    grades: 'PVC Coated Standard',
    applications: 'Boundary Fencing, Garden Fencing, Pet Enclosures, Sports Courts, Farm Partitions',
    price_from: '₹55/sqft',
    meta_title: 'PVC Mesh Supplier in Noida | PVC Coated Welded Wire Mesh 4ft-6.5ft',
    meta_description: 'PVC mesh in Noida from Garg Industrial Mesh. PVC coated welded wire mesh in 4ft, 4.5ft, 5ft & 6.5ft for fencing & enclosures. Weatherproof, long-lasting. Get quote.',
    meta_keywords: 'pvc mesh, pvc coated mesh, pvc welded mesh, pvc mesh noida, pvc mesh 4ft, pvc mesh supplier, pvc fencing mesh',
    featured: 1
  },
  {
    name: 'Aluminium Door Mesh',
    category: 'Door & Window Mesh',
    short_desc: 'Aluminium door mesh in 2ft to 5ft widths — lightweight insect and ventilation mesh for doors.',
    description: 'Aluminium Door Mesh is a lightweight, corrosion-resistant woven mesh designed for door and window frames. Available in 2ft, 2.5ft, 3ft, 3.5ft, 4ft and 5ft widths, it keeps insects out while allowing airflow. Ideal for homes, kitchens, hospitals and commercial spaces in Noida, Greater Noida and Delhi NCR.',
    materials: 'Aluminium Wire',
    sizes: '2ft, 2.5ft, 3ft, 3.5ft, 4ft, 5ft widths; standard mesh opening; rolls & cut pieces',
    grades: 'Aluminium Standard',
    applications: 'Door Screens, Window Screens, Kitchen Ventilation, Hospitals, Commercial Spaces',
    price_from: '₹70/sqft',
    meta_title: 'Aluminium Door Mesh Supplier in Noida | Aluminium Insect Mesh 2ft-5ft',
    meta_description: 'Aluminium door mesh in Noida from Garg Industrial Mesh. Lightweight aluminium insect mesh in 2ft to 5ft widths for doors & windows. Corrosion-resistant. Get quote.',
    meta_keywords: 'aluminium door mesh, aluminium mesh, aluminium insect mesh, door mesh noida, aluminium door mesh supplier, window mesh',
    featured: 1
  },
  {
    name: 'Chain Link Fence',
    category: 'Fencing Mesh',
    short_desc: 'Chain link fencing in 3.5ft, 4.5ft and 5ft heights — strong, economical boundary security.',
    description: 'Chain Link Fence is a woven diamond-pattern fence made from GI or PVC-coated wire. Available in 3.5ft, 4.5ft and 5ft heights, it provides strong, see-through boundary security for plots, factories, farms, sports fields and highways in Noida, Ghaziabad and Delhi NCR. Easy to install and economical per running foot.',
    materials: 'GI Wire / PVC Coated Wire',
    sizes: '3.5ft, 4.5ft, 5ft heights; mesh 25mm to 75mm; wire 1.6mm to 4mm; rolls',
    grades: 'GI / PVC Coated',
    applications: 'Boundary Security, Plots, Factories, Farms, Sports Fields, Highways',
    price_from: '₹50/sqft',
    meta_title: 'Chain Link Fence Supplier in Noida | 3.5ft, 4.5ft & 5ft Chain Link Fencing',
    meta_description: 'Chain link fence in Noida from Garg Industrial Mesh. GI & PVC coated chain link fencing in 3.5ft, 4.5ft & 5ft for boundary security. Best prices per running foot. Get quote.',
    meta_keywords: 'chain link fence, chain link fencing, chain link fence noida, chain link fence supplier, gi chain link fence, pvc chain link fence',
    featured: 1
  },
  {
    name: 'Bird Mesh',
    category: 'Protection Mesh',
    short_desc: 'Bird mesh for balconies, windows and open spaces — keeps birds out without blocking the view.',
    description: 'Bird Mesh is a fine, UV-stabilised nylon or PVC-coated mesh installed on balconies, windows, ducts and open spaces to prevent birds from entering without obstructing light or ventilation. Lightweight, durable and discreet — popular in apartments and offices across Noida, Greater Noida and Delhi NCR.',
    materials: 'Nylon / PVC Coated Wire',
    sizes: 'Standard rolls; opening 12mm to 25mm; cut to size',
    grades: 'Nylon / PVC Coated',
    applications: 'Balconies, Windows, Ducts, Open Spaces, Apartments, Offices',
    price_from: '₹30/sqft',
    meta_title: 'Bird Mesh Supplier in Noida | Bird Protection Mesh for Balconies & Windows',
    meta_description: 'Bird mesh in Noida from Garg Industrial Mesh. Fine nylon & PVC bird protection mesh for balconies, windows & ducts. Keeps birds out, keeps view open. Get quote.',
    meta_keywords: 'bird mesh, bird protection mesh, bird mesh noida, balcony bird mesh, bird mesh supplier, anti bird mesh',
    featured: 0
  },
  {
    name: 'Bird Spikes',
    category: 'Protection Mesh',
    short_desc: 'Bird spikes in stainless steel and plastic — humane bird control for ledges and rooftops.',
    description: 'Bird Spikes are pointed strips fixed to ledges, parapets, rooftops and AC units to humanely prevent birds from landing and nesting. Available in stainless steel (long-lasting, weatherproof) and plastic (economical) variants. Widely used for residential and commercial buildings in Noida and Delhi NCR.',
    materials: 'Stainless Steel / Plastic',
    sizes: 'Standard strips; SS and plastic variants; per foot',
    grades: 'SS, Plastic',
    applications: 'Ledges, Parapets, Rooftops, AC Units, Signage, Residential & Commercial Buildings',
    price_from: '₹40/ft',
    meta_title: 'Bird Spikes Supplier in Noida | SS & Plastic Bird Control Spikes',
    meta_description: 'Bird spikes in Noida from Garg Industrial Mesh. Stainless steel & plastic bird control spikes for ledges, rooftops & AC units. Humane, durable. Best prices. Get quote.',
    meta_keywords: 'bird spikes, bird control spikes, ss bird spikes, plastic bird spikes, bird spikes noida, bird spikes supplier, anti bird spikes',
    featured: 1
  },
  {
    name: 'Monkey Spikes',
    category: 'Protection Mesh',
    short_desc: 'Monkey spikes to deter monkeys from ledges, walls and rooftops — humane and effective.',
    description: 'Monkey Spikes are robust pointed strips installed on ledges, boundary walls, rooftops and AC platforms to humanely deter monkeys from climbing and sitting. Made from durable metal, they protect property and people in monkey-prone areas of Noida, Greater Noida and Delhi NCR without harming the animals.',
    materials: 'Galvanised / Stainless Steel',
    sizes: 'Standard strips; per foot; custom lengths',
    grades: 'GI / SS',
    applications: 'Ledges, Boundary Walls, Rooftops, AC Platforms, Residential & Commercial Buildings',
    price_from: '₹55/ft',
    meta_title: 'Monkey Spikes Supplier in Noida | Anti-Monkey Spikes for Walls & Rooftops',
    meta_description: 'Monkey spikes in Noida from Garg Industrial Mesh. Durable anti-monkey spikes for ledges, walls & rooftops. Humane, effective monkey control. Best prices. Get quote.',
    meta_keywords: 'monkey spikes, anti monkey spikes, monkey spikes noida, monkey control spikes, monkey spikes supplier, monkey protection spikes',
    featured: 0
  },
  {
    name: 'Construction Net',
    category: 'Safety Net',
    short_desc: 'Construction safety netting for scaffolding, debris and fall protection on building sites.',
    description: 'Construction Net is a high-strength HDPE safety net used on scaffolding, building facades and open edges to catch debris and protect workers from falls. UV-stabilised for outdoor durability, it meets site safety requirements for high-rise and infrastructure projects across Noida, Greater Noida and Delhi NCR.',
    materials: 'HDPE (UV Stabilised)',
    sizes: 'Standard rolls; mesh 25mm to 100mm; cut to size',
    grades: 'HDPE Standard',
    applications: 'Scaffolding, Building Facades, Debris Protection, Fall Protection, Infrastructure Sites',
    price_from: '₹35/sqft',
    meta_title: 'Construction Net Supplier in Noida | Safety & Debris Netting for Sites',
    meta_description: 'Construction net in Noida from Garg Industrial Mesh. HDPE safety & debris netting for scaffolding and building sites. UV-stabilised, site-safe. Best prices. Get quote.',
    meta_keywords: 'construction net, construction safety net, debris net, scaffolding net, construction net noida, construction net supplier, safety netting',
    featured: 0
  }
];

module.exports = { products, slugify, buildFaq };
